### ISSUE TITLE
Can't build on linux, compile errors

### ISSUE THREAD

**Issue by csiszarattila** [PureSwift/SeeURL#1]
Hi,
I cant get compiled this package under linux, I got a bunch of errors, mostly these:

```
Compiling Swift Module 'SeeURL' (6 sources)
/swift/Mailer/Packages/SeeURL-1.0.0/Sources/SeeURL/cURL.swift:167:2: error: unknown attribute 'asmname'
@asmname("curl_easy_setopt") public func curl_easy_setopt(curl: cURL.Handler, option: cURL.Option, param: UnsafePointer<UInt8>) -> CURLcode
^
/swift/Mailer/Packages/SeeURL-1.0.0/Sources/SeeURL/cURL.swift:167:9: error: expected declaration
@asmname("curl_easy_setopt") public func curl_easy_setopt(curl: cURL.Handler, option: cURL.Option, param: UnsafePointer<UInt8>) -> CURLcode
    ^
/swift/Mailer/Packages/SeeURL-1.0.0/Sources/SeeURL/HTTPClient.swift:11:12: error: missing required modules: 'CJSONC', 'CStatfs', 'CUUID'
 import SwiftFoundation
       ^
```

My swift version is the latest:

```
# swift --version
Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 42591f7cba)
Target: x86_64-unknown-linux-gnu
```

What should I do to make it working?

**Comment by colemancda** [comment]
so.. Yeah, this stopped working on Swift 2.2. The issue is that important cURL functions, are macros, so the `@asmname("symbol_name")` could find hidden (or private) functions. Right now I don't see any solution to this issue. Maybe a simple C header file would suffice?

**Comment by colemancda** [comment]
Added a Swift compatibility header. Since the helper functions are inlined, no need to compile separate library.
